In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('Social_Network_Ads.csv')

In [3]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
df.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [5]:
x=df[['Age', 'EstimatedSalary']].values

In [6]:
y=df['Purchased'].values

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)

In [9]:
x_train.shape

(320, 2)

In [12]:
x_test.shape

(80, 2)

In [20]:
from sklearn.preprocessing import StandardScaler

In [23]:
s_scaler=StandardScaler()

In [25]:
x_train=s_scaler.fit_transform(x_train)

In [27]:
x_test=s_scaler.fit_transform(x_test)

In [29]:
from sklearn.ensemble import AdaBoostClassifier

In [37]:
adb=AdaBoostClassifier(n_estimators=50)

In [39]:
adb.fit(x_train,y_train)

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoostClassifier()

In [41]:
y_pre=adb.predict(x_test)

In [43]:
y_pre

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

In [45]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1], dtype=int64)

In [47]:
from sklearn.metrics import f1_score,confusion_matrix,accuracy_score,classification_report

In [49]:
f1score=f1_score(y_test,y_pre)

In [51]:
f1score*100

85.71428571428571

In [53]:
confusion_matrix=confusion_matrix(y_test,y_pre)

In [55]:
confusion_matrix

array([[56,  2],
       [ 4, 18]], dtype=int64)

In [57]:
accuracy_score=accuracy_score(y_test,y_pre)

In [59]:
accuracy_score*100

92.5

In [61]:
print(classification_report(y_test,y_pre))


              precision    recall  f1-score   support

           0       0.93      0.97      0.95        58
           1       0.90      0.82      0.86        22

    accuracy                           0.93        80
   macro avg       0.92      0.89      0.90        80
weighted avg       0.92      0.93      0.92        80

