In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df=pd.read_csv('Social_Network_Ads.csv')

In [9]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [11]:
x=df[['Age','EstimatedSalary']].values

In [13]:
y=df['Purchased'].values

In [15]:
from sklearn.model_selection import train_test_split

In [17]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)

In [19]:
x_train.shape

(320, 2)

In [21]:
x_test.shape

(80, 2)

In [23]:
from sklearn.preprocessing import StandardScaler

In [25]:
s_scaler=StandardScaler()

In [27]:
x_train=s_scaler.fit_transform(x_train)

In [29]:
x_test=s_scaler.fit_transform(x_test)

In [31]:
x_train.shape

(320, 2)

In [33]:
x_test.shape

(80, 2)

In [35]:
from sklearn.neighbors import KNeighborsClassifier

In [37]:
knn=KNeighborsClassifier(n_neighbors=3)

In [39]:
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [41]:
y_pre=knn.predict(x_test)

In [43]:
y_pre

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1], dtype=int64)

In [45]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1], dtype=int64)

In [65]:
from  sklearn.metrics import f1_score

In [73]:
f1score=f1_score(y_test,y_pre)

In [75]:
f1score*100

89.36170212765957

In [77]:
from  sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [79]:
accuracy=accuracy_score(y_test,y_pre)

In [81]:
accuracy * 100

93.75

In [85]:
print(classification_report(y_test,y_pre))

              precision    recall  f1-score   support

           0       0.98      0.93      0.96        58
           1       0.84      0.95      0.89        22

    accuracy                           0.94        80
   macro avg       0.91      0.94      0.92        80
weighted avg       0.94      0.94      0.94        80



In [87]:
matrix=confusion_matrix(y_test,y_pre)

In [89]:
matrix

array([[54,  4],
       [ 1, 21]], dtype=int64)