In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
df=pd.read_csv('Salary_Data.csv')

In [12]:
df.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [13]:
x=df[['YearsExperience']].values

In [14]:
x

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [15]:
y=df['Salary'].values

In [16]:
y

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)

In [28]:
x_train.shape

(24, 1)

In [30]:
x_test

array([[ 1.5],
       [10.3],
       [ 4.1],
       [ 3.9],
       [ 9.5],
       [ 8.7]])

In [32]:
from sklearn.neighbors import KNeighborsRegressor

In [34]:
knn=KNeighborsRegressor(n_neighbors=3)

In [36]:
knn.fit(x_train,y_train)

KNeighborsRegressor(n_neighbors=3)

In [38]:
y_pred=knn.predict(x_test)

In [42]:
y_pred

array([ 43024.33333333, 113363.        ,  56646.66666667,  56646.66666667,
       113363.        , 106898.66666667])

In [52]:
y_test

array([ 37731., 122391.,  57081.,  63218., 116969., 109431.])

In [54]:
from sklearn.metrics import r2_score

In [56]:
r2_score(y_test,y_pred)*100

97.35051713340684