In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df=pd.read_csv('Social_Network_Ads.csv')

In [7]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [13]:
x=df[['Age','EstimatedSalary']].values

In [15]:
y=df['Purchased'].values

In [25]:
from sklearn.model_selection import train_test_split

In [27]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)

In [29]:
x_train.shape

(320, 2)

In [31]:
x_test.shape

(80, 2)

In [33]:
from sklearn.preprocessing import StandardScaler

In [35]:
s_scaler=StandardScaler()

In [39]:
x_train=s_scaler.fit_transform(x_train)

In [41]:
x_test=s_scaler.fit_transform(x_test)

In [43]:
from sklearn.ensemble import RandomForestClassifier

In [45]:
RFC=RandomForestClassifier()

In [47]:
RFC.fit(x_train,y_train)

RandomForestClassifier()

In [49]:
y_pre=RFC.predict(x_test)

In [51]:
y_pre

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1], dtype=int64)

In [53]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1], dtype=int64)

In [57]:
from sklearn.metrics import f1_score,confusion_matrix,accuracy_score,classification_report

In [59]:
f1score=f1_score(y_test,y_pre)

In [63]:
f1score*100

86.95652173913044

In [65]:
confusion_matrix=confusion_matrix(y_test,y_pre)

In [67]:
confusion_matrix

array([[54,  4],
       [ 2, 20]], dtype=int64)

In [69]:
accuracy=accuracy_score(y_test,y_pre)

In [73]:
accuracy*100

92.5

In [75]:
print(classification_report(y_test,y_pre))

              precision    recall  f1-score   support

           0       0.96      0.93      0.95        58
           1       0.83      0.91      0.87        22

    accuracy                           0.93        80
   macro avg       0.90      0.92      0.91        80
weighted avg       0.93      0.93      0.93        80

